### PR TITLE
Move to python3 and zeep

### PR DESCRIPTION
**Pull request by wonko21**
* 2to3
* absolute instead of relative imports
* zeep replaces suds

### CODE REVIEW

**Comment by rsteube** [comment]
nice :+1:
- `flik.common` import fails on python2 (probably should still support it for OSX)
- `flik sync` and completion for `flik add` seems to be broken
- zeep had a bug handling a specific response from the server which is why i waited for that to be fixed (might be ok by now)
will try to have a closer look soon, would be nice to finally migrate to py3

**Comment by wonko21** [comment]
- probably should still support it for OSX ... not a good idea: https://pythonclock.org/ we should force users away asap
- flik sync and completion for flik add seems to be broken
works on my machine
- zeep had a bug handling a specific response from the server which is why i waited for that to be fixed (might be ok by now)
which one? shall i test? I am currently adding support for work-hours ( as in should work x hours) and vacations

**Comment by rsteube** [comment]
- **python3**: ok let's migrate, but we probably should add versions for dependencies in setup.py then
- **sync**: fails on my machine on extractTasks (too many values to unpack)
with this change projects and task sync seem to work:
```python
  def extractTasks(task, prefix=''):
      result = {}
      if task.worktimeAllowed:
          result[quote(prefix + task.name)] = str(task.taskID)

      if task.children is not None:
          for subTask in task.children.WorkTimeTask:
              result.update(extractTasks(subTask, task.name + '__'))
      return result
```
but activities still fail - looking into that now

**Comment by rsteube** [comment]
`defaultvalue` needs to be set now
```python
  def syncActivities():
    raw_activities = client().service.getActivities(
            sessionID=sessionID(),
            defaultvalue=False)
```
had to remove all the encode/decode calls (should test edge cases with special charactes though)
you sure you haven't accidentally testet the old pip2 version?

**zeep error**: cannot handle simple numbers as result at the moment (there was already an issue open regarding this error)
```python
  File "/home/rsteube/.local/lib/python3.6/site-packages/zeep/wsdl/messages/soap.py", line 104, in deserialize
    if result is None or len(result) == 0:
TypeError: object of type 'int' has no len()
```

**see** https://github.com/rsteube/flik/tree/py3

**Pull request closed without merging**
